### ISSUE TITLE
Buy /bid process for OU

### ISSUE THREAD

**Issue by nchen000** [JiejayLan/CSC322_group_project#19]

**Comment by shiBinH** [comment]
From the project requirements, the purchase order initiated by a buyer/winning bidder needs approval from the seller before the order can be completed. Perhaps the user profile page #16 should provide access to the orders that the user needs to review and process? Also a page to review approve/disapprove specific orders will probably be needed. The feature should provide the client a way to explain why he rejected the seller. The explanation can probably be sent to the buyer through the messaging service, which we need to implement and which all OUs have access.

Heres a brief sketch of the possible flow of a purchase:

![Untitled Diagram (1)](https://user-images.githubusercontent.com/16170334/55659578-586f1600-57d0-11e9-805b-a0ff39ae0df9.png)

**Comment by JiejayLan** [comment]
I think a should be a separate page for each user to display all the orders status.
1.finish(approve or disapprove)
2. pending order he want to buy,
3.pending order he need to confirm to sell). 
You can use a nav bar to control these these components

No need to combine with user profile page #16.  For pending order he need to confirm to sell, just two button next to it, agree or deny. For the message system, we don't need to worry about that now. 

You can work at this order status page, after that complete the make an order/bid function on the item page.

**Comment by shiBinH** [comment]
Actually I can probably finish working on the items page first. Any items that are successfully bought/bid for will be logged into the database as a pending order for which the seller can review when we have the order review page ready.

**Comment by JiejayLan** [comment]
Yes, no problem

**Comment by shiBinH** [comment]
For items open to bidding, I am going to set up a timer on the server side that checks if the auction time for the item has passed. If the auction has ended then a pending order is created for that item. So then the item application should provide an option to select a time for when he wants to end bidding for the item @JiejayLan
