### ISSUE TITLE
set up package.json problem

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/CSC322_group_project#27]
If we use webpack-dev-server to run our code, it didn't involve the server. When I need to do edit the server.js file. I have to use "npm run start". But this script command can't auto rebuild the webpack.  After that, I try to combine "build webpack" and "nodemon server.js" into one script command, but it didn't work. 
This is how I set up for my other project. When I run "npm run deve", everything works fine. But not for our repo.
![image](https://user-images.githubusercontent.com/37095411/55672802-498a7100-586d-11e9-8fc2-6001c7417581.png)

**Comment by shiBinH** [comment]
I think running the commands on separate terminals works.

**Comment by JiejayLan** [comment]
I think i find out the reason. In my our repo, there is a "watch:true" setting to watch if any front end update
